kind: PersistentVolume
apiVersion: v1
metadata:
  name: etcd-pv-volume
  labels:
    app: openpitrix
    tier: etcd
spec:
  capacity:
    storage: 10Gi
  storageClassName: openpitrix-etcd-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
