apiVersion: v1
kind: Service
metadata:
  name: openpitrix-etcd
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    tier: etcd
    version: ${VERSION}
spec:
  selector:
    app: openpitrix
    tier: etcd
  ports:
  - name: tcp
    protocol: TCP
    port: 2379
    targetPort: 2379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openpitrix-etcd-pvc
  namespace: ${NAMESPACE}
  annotations:
    volume.beta.kubernetes.io/storage-class: openpitrix-etcd-pv
  labels:
    app: openpitrix
    tier: etcd
spec:
  storageClassName: openpitrix-etcd-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-etcd-deployment
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    tier: etcd
    version: ${VERSION}
spec:
  selector:
    matchLabels:
      app: openpitrix
      tier: etcd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openpitrix
        tier: etcd
        version: ${VERSION}
    spec:
      containers:
      - name: openpitrix-etcd
        image: quay.io/coreos/etcd:v3.2.18
        imagePullPolicy: IfNotPresent
        command: ["etcd", "--data-dir=/data", "--listen-client-urls=http://0.0.0.0:2379", "--advertise-client-urls=http://openpitrix-etcd.${NAMESPACE}.svc:2379", "--max-snapshots=5", "--max-wals=5", "--auto-compaction-retention=168"]
        ports:
        - containerPort: 2379
          name: etcd
        volumeMounts:
        - name: etcd-persistent-storage
          mountPath: /data
      volumes:
      - name: etcd-persistent-storage
        persistentVolumeClaim:
          claimName: openpitrix-etcd-pvc
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: etcd-pv-volume
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    tier: etcd
spec:
  storageClassName: openpitrix-etcd-pv
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: openpitrix-etcd-pv
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
