version: '3.1'
services:
  db:
    image: bitnami/mongodb
    restart: always
    environment:
      MONGODB_USERNAME: test
      MONGODB_PASSWORD: test
      MONGODB_DATABASE: test
    volumes:
      - /var/lib/data:/bitnami

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
