kind: Service
apiVersion: v1
metadata:
  name: kubeapps-nodeport
  namespace: kubeapps
spec:
  selector:
    app: kubeapps
    release: kubeapps
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
